### ISSUE TITLE
Separate Symfony services from your application services

### ISSUE THREAD

**Issue by javiereguiluz** [EasyCorp/easy-doc-bundle#10]
This issue requires to have fixed #8 first.

---

### Problem

We are thinking about separating the internal Symfony services from the services defined by your application.

### Solution

To do so, we need to update the `DocCommand::getServices()` method to add a `is_internal` element to the array that holds the service information. And we need a reliable way to detect if a service is internal to Symfony or not.

---

We could even divide services into `symfony`, vendor bundles (assetic, FOS, etc.) and your own services defined in your application code.

**Comment by stof** [comment]
Related to #3
