### ISSUE TITLE
Add a new panel to show Entities information

### ISSUE THREAD

**Issue by javiereguiluz** [EasyCorp/easy-doc-bundle#16]
What information should we display in this panel?

**Comment by javiereguiluz** [comment]
In the Symfony Slack, a user suggested this:

> I thought about showing there auto-generated UML schema (for example by Pulpo) https://www.pulpo18.com ? I don't know how long will this take me, but if you aren't working on this I can start right now

I think copying that feature would be crazy ... but showing the same information in a less fancy way (i.e. with a simple table) could be doable.

**Comment by mleczakm** [comment]
I thought about using pulpo for generating schema cause It would be quite easy to implement. It is not available through composer but I think it can be fixed for example by putting it on some server with simple API or adding linux version to composer. Personally I don't find UML schema useful for anyone, but seems that PM's like to have something colorful in docs.

Entities should have all info from XML mapping, including relation type and link to second side (anchor to another entity). Maybe there is existing auto-doc app for another language and we could take a look?

**Comment by javiereguiluz** [comment]
For now we can start just outputting all the information. Later we can add some fancy graphs generated with GraphViz and SVG (I plan to do the same for services).

So, would it be useful for you to just display the information in a normal table instead of a graphic?

**Comment by mleczakm** [comment]
Of course, I can always generate image by myself, 5 seconds :)
