### ISSUE TITLE
Show which roles can access to each route

### ISSUE THREAD

**Issue by javiereguiluz** [EasyCorp/easy-doc-bundle#17]
I don't know if this is possible, but in the Symfony Slack, a person asked for this feature. He also give me this reference: https://github.com/jdecoster/RoutingExtraBundle

I guess it's doable for `access_control` configuration ... but for roles defined in expressions inside `@Security` or for highly dynamic security features (voters, checks inside the controller methods, etc.) it would be "impossible".

**Comment by linaori** [comment]
What you _can_ show, is a detailed set of rules per route. You can aggregate the values of the annotation and access control to do so. This is as close to what the request seems to be as possible in my eyes.
