### ISSUE TITLE
Separate Symfony routes from your application routes

### ISSUE THREAD

**Issue by javiereguiluz** [EasyCorp/easy-doc-bundle#9]
This issue requires to have fixed #7 first.

---

### Problem

We are thinking about separating the internal Symfony routes (profiler, assetic, Twig error preview) from the routes defined by your application.

### Solution

To do so, we need to update the `DocCommand::getRoutes()` method to add a `is_internal` element to the array that holds the route information. And we need a reliable way to detect if a route is internal to Symfony or not.

---

We could even divide routes into `symfony` (profiler, Twig error preview), vendor bundles (assetic, FOS, etc.) and your own routes defined in your application code.

**Comment by linaori** [comment]
A route is connected to a controller most of the time. If this is the case, you can reflect on that controller and get the path. Grab the vendor directory from the composer.lock and you can tell if the controller is a vendor controller (not if the route is vendor). It's not completely reliable, but it's something.

**Comment by stof** [comment]
For routes of the profiler, Twig error preview and Assetic, these could be matched by name (they are all prefixed with a known string). I doubt people will really define their own ``_assetic_*`` routes (which could cause conflicts with AsseticBundle btw).
Symfony does not add internal routes that often, so it may be fine to hardcode a list of internal route name patterns
